/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgres://username:password@localhost:5432/social -t migrations -t profiles -t providers -t sessions -t users -t verifications -s public
 *
 */


export type Json = unknown;
export type providers_provider_enum = 'google' | 'magic' | 'password';
export type verifications_type_enum = 'email' | 'magic_link' | 'password_reset';

// Table migrations
export interface Migrations {
  id: number;
  timestamp: number;
  name: string;
}
export interface MigrationsInput {
  id?: number;
  timestamp: number;
  name: string;
}
const migrations = {
  tableName: 'migrations',
  columns: ['id', 'timestamp', 'name'],
  requiredForInsert: ['timestamp', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Migrations,
  $input: null as unknown as MigrationsInput
} as const;

// Table profiles
export interface Profiles {
  id: number;
  userId: number;
  name: string;
  avatarUrl: string | null;
  bio: string | null;
  postsCount: number;
  followersCount: number;
  followingCount: number;
  createdAt: Date;
  updatedAt: Date;
  username: string;
}
export interface ProfilesInput {
  id?: number;
  userId: number;
  name: string;
  avatarUrl?: string | null;
  bio?: string | null;
  postsCount?: number;
  followersCount?: number;
  followingCount?: number;
  createdAt?: Date;
  updatedAt?: Date;
  username: string;
}
const profiles = {
  tableName: 'profiles',
  columns: ['id', 'userId', 'name', 'avatarUrl', 'bio', 'postsCount', 'followersCount', 'followingCount', 'createdAt', 'updatedAt', 'username'],
  requiredForInsert: ['userId', 'name', 'username'],
  primaryKey: 'id',
  foreignKeys: { userId: { table: 'users', column: 'id', $type: null as unknown as Users }, },
  $type: null as unknown as Profiles,
  $input: null as unknown as ProfilesInput
} as const;

// Table providers
export interface Providers {
  id: number;
  provider: providers_provider_enum;
  providerId: string;
  createdAt: Date;
  userId: number | null;
}
export interface ProvidersInput {
  id?: number;
  provider: providers_provider_enum;
  providerId: string;
  createdAt?: Date;
  userId?: number | null;
}
const providers = {
  tableName: 'providers',
  columns: ['id', 'provider', 'providerId', 'createdAt', 'userId'],
  requiredForInsert: ['provider', 'providerId'],
  primaryKey: 'id',
  foreignKeys: { userId: { table: 'users', column: 'id', $type: null as unknown as Users }, },
  $type: null as unknown as Providers,
  $input: null as unknown as ProvidersInput
} as const;

// Table sessions
export interface Sessions {
  id: number;
  refreshTokenHash: string;
  expiresAt: Date;
  ip: string | null;
  userAgent: string | null;
  device: string | null;
  platform: string | null;
  location: string | null;
  lastUsedAt: Date | null;
  revokedAt: Date | null;
  createdAt: Date;
  userId: number | null;
}
export interface SessionsInput {
  id?: number;
  refreshTokenHash: string;
  expiresAt: Date;
  ip?: string | null;
  userAgent?: string | null;
  device?: string | null;
  platform?: string | null;
  location?: string | null;
  lastUsedAt?: Date | null;
  revokedAt?: Date | null;
  createdAt?: Date;
  userId?: number | null;
}
const sessions = {
  tableName: 'sessions',
  columns: ['id', 'refreshTokenHash', 'expiresAt', 'ip', 'userAgent', 'device', 'platform', 'location', 'lastUsedAt', 'revokedAt', 'createdAt', 'userId'],
  requiredForInsert: ['refreshTokenHash', 'expiresAt'],
  primaryKey: 'id',
  foreignKeys: { userId: { table: 'users', column: 'id', $type: null as unknown as Users }, },
  $type: null as unknown as Sessions,
  $input: null as unknown as SessionsInput
} as const;

// Table users
export interface Users {
  id: number;
  email: string;
  passwordHash: string | null;
  isVerified: boolean;
  createdAt: Date;
  updatedAt: Date;
}
export interface UsersInput {
  id?: number;
  email: string;
  passwordHash?: string | null;
  isVerified?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}
const users = {
  tableName: 'users',
  columns: ['id', 'email', 'passwordHash', 'isVerified', 'createdAt', 'updatedAt'],
  requiredForInsert: ['email'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Users,
  $input: null as unknown as UsersInput
} as const;

// Table verifications
export interface Verifications {
  id: number;
  tokenHash: string;
  codeHash: string | null;
  attempts: number;
  type: verifications_type_enum;
  expiresAt: Date;
  usedAt: Date | null;
  metadata: Json | null;
  email: string | null;
  createdAt: Date;
  userId: number | null;
}
export interface VerificationsInput {
  id?: number;
  tokenHash: string;
  codeHash?: string | null;
  attempts?: number;
  type: verifications_type_enum;
  expiresAt: Date;
  usedAt?: Date | null;
  metadata?: Json | null;
  email?: string | null;
  createdAt?: Date;
  userId?: number | null;
}
const verifications = {
  tableName: 'verifications',
  columns: ['id', 'tokenHash', 'codeHash', 'attempts', 'type', 'expiresAt', 'usedAt', 'metadata', 'email', 'createdAt', 'userId'],
  requiredForInsert: ['tokenHash', 'type', 'expiresAt'],
  primaryKey: 'id',
  foreignKeys: { userId: { table: 'users', column: 'id', $type: null as unknown as Users }, },
  $type: null as unknown as Verifications,
  $input: null as unknown as VerificationsInput
} as const;


export interface TableTypes {
  migrations: {
    select: Migrations;
    input: MigrationsInput;
  };
  profiles: {
    select: Profiles;
    input: ProfilesInput;
  };
  providers: {
    select: Providers;
    input: ProvidersInput;
  };
  sessions: {
    select: Sessions;
    input: SessionsInput;
  };
  users: {
    select: Users;
    input: UsersInput;
  };
  verifications: {
    select: Verifications;
    input: VerificationsInput;
  };
}

export const tables = {
  migrations,
  profiles,
  providers,
  sessions,
  users,
  verifications,
}
